// TCM Five Element Quiz Data
// Each question has 5 options, one per element (wood, fire, earth, metal, water)

export const ELEMENTS = {
  wood: {
    key: "wood",
    name: "Wood",
    chinese: "木",
    color: "#5A7156",
    bg: "#EAF0E5",
    accent: "#3E533B",
    season: "Spring",
    organ: "Liver & Gallbladder",
    emotion: "Anger ↔ Kindness",
    virtue: "Vision · Growth · Decisiveness",
    tagline: "The Visionary Pioneer",
    description:
      "You are a natural leader with a clear vision and an unstoppable drive to grow. Like a young sapling pushing through soil, you turn obstacles into opportunities. Your energy is expansive, your mind strategic, and your spirit ambitious.",
    strengths: ["Decisive & strategic", "Strong sense of direction", "Pioneering courage", "Loyal to a cause"],
    imbalance: ["Frustration & irritability", "Tension headaches", "Tight shoulders/jaw", "Impatience"],
    tips: [
      "Stretch daily — especially side body, hips, and shoulders to free liver Qi.",
      "Add sour foods (lemon, vinegar, sour apple) to your meals.",
      "Take walks in green spaces; nature recalibrates Wood energy.",
      "Practice slow breathing before reacting — your fire ignites fast.",
    ],
  },
  fire: {
    key: "fire",
    name: "Fire",
    chinese: "火",
    color: "#B05B43",
    bg: "#F8E7E0",
    accent: "#8E3F2C",
    season: "Summer",
    organ: "Heart & Small Intestine",
    emotion: "Anxiety ↔ Joy",
    virtue: "Passion · Connection · Charisma",
    tagline: "The Radiant Connector",
    description:
      "You light up every room you enter. Warm, expressive, and deeply social, you live for connection, laughter, and the thrill of being alive. When balanced, your joy is contagious; when overdrawn, you burn the candle from both ends.",
    strengths: ["Charismatic & magnetic", "Quick-witted & playful", "Empathetic listener", "Inspires others"],
    imbalance: ["Insomnia & restlessness", "Palpitations", "Overthinking", "Burnout from over-giving"],
    tips: [
      "Protect rest like a sacred ritual — sleep before 11 PM.",
      "Add bitter greens (rocket, dandelion, dark chocolate) to cool excess fire.",
      "Schedule alone-time; your battery drains in crowds.",
      "Practice silence — meditation calms an over-stimulated heart.",
    ],
  },
  earth: {
    key: "earth",
    name: "Earth",
    chinese: "土",
    color: "#C89F5A",
    bg: "#F5ECD8",
    accent: "#8E6F2C",
    season: "Late Summer",
    organ: "Spleen & Stomach",
    emotion: "Worry ↔ Empathy",
    virtue: "Nurture · Stability · Devotion",
    tagline: "The Grounded Nurturer",
    description:
      "You are the steady center friends, family, and colleagues lean on. Warm-hearted, dependable and deeply empathetic, your gift is making people feel held. Like fertile soil, you nourish everything that grows around you.",
    strengths: ["Reliable & loyal", "Deeply empathetic", "Excellent mediator", "Patient & thoughtful"],
    imbalance: ["Bloating & sluggish digestion", "Overthinking / worry loops", "Heaviness & fatigue", "Difficulty saying no"],
    tips: [
      "Eat warm, cooked foods — your spleen dislikes raw & cold.",
      "Add naturally sweet roots (sweet potato, carrot, pumpkin) to meals.",
      "Set one small daily boundary — your generosity needs a fence.",
      "Move gently — walks and Qi Gong move stagnant Earth energy.",
    ],
  },
  metal: {
    key: "metal",
    name: "Metal",
    chinese: "金",
    color: "#9CA3A1",
    bg: "#EFEEEC",
    accent: "#5F6663",
    season: "Autumn",
    organ: "Lungs & Large Intestine",
    emotion: "Grief ↔ Reverence",
    virtue: "Precision · Integrity · Refinement",
    tagline: "The Refined Architect",
    description:
      "You move through the world with elegance, precision and quiet authority. You value quality over quantity, structure over chaos. People trust your judgment because you see clearly what others miss. You are the standard-setter.",
    strengths: ["Disciplined & organized", "Refined taste", "Principled & honest", "Sees the essential clearly"],
    imbalance: ["Shallow breathing", "Dry skin", "Difficulty letting go", "Perfectionism & isolation"],
    tips: [
      "Practice deep diaphragmatic breathing 5 min/day.",
      "Add pungent foods (ginger, garlic, radish) to open the lungs.",
      "Declutter one drawer weekly — outer order soothes inner Metal.",
      "Allow grief its passage; suppressed sadness weakens lungs.",
    ],
  },
  water: {
    key: "water",
    name: "Water",
    chinese: "水",
    color: "#3E4E59",
    bg: "#E2E7EB",
    accent: "#1F2E38",
    season: "Winter",
    organ: "Kidneys & Bladder",
    emotion: "Fear ↔ Wisdom",
    virtue: "Depth · Wisdom · Will",
    tagline: "The Deep Sage",
    description:
      "You are the quiet philosopher, the deep well others come to drink from. Reflective, intuitive and resourceful, you carry an ancient stillness. Your power comes from going deep, not wide — and from conserving energy for what truly matters.",
    strengths: ["Deeply intuitive", "Reservoir of inner strength", "Strategic & long-view", "Thrives in solitude"],
    imbalance: ["Lower back / knee weakness", "Cold hands & feet", "Fearfulness & withdrawal", "Adrenal exhaustion"],
    tips: [
      "Sleep is medicine — your kidneys recharge in deep rest.",
      "Add black foods (black sesame, black beans, seaweed) to nourish Water.",
      "Stay warm — protect your lower back & feet from cold.",
      "Honor solitude, but don't isolate; depth needs occasional sunlight.",
    ],
  },
};

export const QUESTIONS = [
  {
    id: "q1",
    text: "When facing a new challenge, your instinctive first move is to…",
    options: [
      { element: "wood", label: "Set a clear goal and start advancing immediately" },
      { element: "fire", label: "Rally people, brainstorm, and feel the excitement" },
      { element: "earth", label: "Check in with everyone involved and find common ground" },
      { element: "metal", label: "Step back, analyze, and design the precise plan" },
      { element: "water", label: "Sit with it quietly until the deeper pattern emerges" },
    ],
  },
  {
    id: "q2",
    text: "Friends would describe your natural energy as…",
    options: [
      { element: "wood", label: "Driven, bold, and pioneering" },
      { element: "fire", label: "Warm, magnetic, and expressive" },
      { element: "earth", label: "Caring, dependable, and grounding" },
      { element: "metal", label: "Refined, principled, and composed" },
      { element: "water", label: "Reflective, mysterious, and wise" },
    ],
  },
  {
    id: "q3",
    text: "Which season makes you feel most alive?",
    options: [
      { element: "wood", label: "Spring — everything bursting open" },
      { element: "fire", label: "Summer — long, warm, alive evenings" },
      { element: "earth", label: "Late summer — golden, harvest abundance" },
      { element: "metal", label: "Autumn — crisp clarity, falling leaves" },
      { element: "water", label: "Winter — quiet, still, deep" },
    ],
  },
  {
    id: "q4",
    text: "Under stress, your body usually tells you first through…",
    options: [
      { element: "wood", label: "Tight shoulders, jaw or headaches" },
      { element: "fire", label: "Racing heart, insomnia, restlessness" },
      { element: "earth", label: "Bloating, sweet cravings, heaviness" },
      { element: "metal", label: "Shallow breath, dry skin, congestion" },
      { element: "water", label: "Lower back ache, fatigue, cold feet" },
    ],
  },
  {
    id: "q5",
    text: "Your ideal way to recharge after a long week is…",
    options: [
      { element: "wood", label: "An adventurous hike or new challenge" },
      { element: "fire", label: "A vibrant evening with close friends" },
      { element: "earth", label: "Cooking a slow meal at home" },
      { element: "metal", label: "Tidying your space and journaling" },
      { element: "water", label: "Solitude, a long bath, a deep book" },
    ],
  },
  {
    id: "q6",
    text: "Which flavor are you most drawn to?",
    options: [
      { element: "wood", label: "Sour — lemon, vinegar, pickles" },
      { element: "fire", label: "Bitter — dark chocolate, coffee, greens" },
      { element: "earth", label: "Sweet — roots, grains, ripe fruit" },
      { element: "metal", label: "Pungent — ginger, garlic, mustard" },
      { element: "water", label: "Salty — seaweed, miso, broths" },
    ],
  },
  {
    id: "q7",
    text: "In a disagreement, you tend to…",
    options: [
      { element: "wood", label: "State your position firmly and push for resolution" },
      { element: "fire", label: "Speak passionately and hope warmth wins them over" },
      { element: "earth", label: "Try to mediate and protect the relationship" },
      { element: "metal", label: "Lay out facts logically and expect fairness" },
      { element: "water", label: "Withdraw, observe, and respond after reflection" },
    ],
  },
  {
    id: "q8",
    text: "Your secret superpower is…",
    options: [
      { element: "wood", label: "Turning vision into bold action" },
      { element: "fire", label: "Making everyone feel seen and alive" },
      { element: "earth", label: "Holding space when others fall apart" },
      { element: "metal", label: "Spotting what is essential vs. noise" },
      { element: "water", label: "Sensing what is coming before it arrives" },
    ],
  },
  {
    id: "q9",
    text: "Your home/workspace ideally feels…",
    options: [
      { element: "wood", label: "Open, plant-filled, room to grow" },
      { element: "fire", label: "Bright, social, full of art and color" },
      { element: "earth", label: "Warm, cozy, kitchen at the center" },
      { element: "metal", label: "Minimal, clean lines, refined objects" },
      { element: "water", label: "Quiet, dim, layered with books" },
    ],
  },
  {
    id: "q10",
    text: "What do you most secretly long for?",
    options: [
      { element: "wood", label: "To build something that outlives me" },
      { element: "fire", label: "To love and be loved fully" },
      { element: "earth", label: "To create a home where everyone belongs" },
      { element: "metal", label: "To live with absolute integrity" },
      { element: "water", label: "To truly understand the nature of things" },
    ],
  },
];
